[package]
name = "rusty-style-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clang = { version = "2.0.0", features = ["clang_10_0"] }
ignore = "0.4.20"
regex = "1.7.3"
